'use client';
import {useEffect,useState} from 'react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {Utensils,Coffee,Check,Plus,Users,CalendarDays,ChartNoAxesCombined,ChevronLeft,ChevronRight} from 'lucide-react';
type Person={id:string;name:string;active:number};type Meal={date:string;personId:string;cents:number;kind:string};type Data={people:Person[];meals:Meal[]};
const euro=(n:number)=>new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR'}).format(n/100);
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Berlin'}).format(new Date());
function nearest(){let d=new Date(today()+'T12:00:00Z');while(![3,5].includes(d.getUTCDay()))d.setUTCDate(d.getUTCDate()-1);return d.toISOString().slice(0,10);}
export default function Home(){const[data,setData]=useState<Data>({people:[],meals:[]});const[loaded,setLoaded]=useState(false);const[date,setDate]=useState(nearest);const[month,setMonth]=useState(()=>today().slice(0,7));const[tab,setTab]=useState('entry');const[error,setError]=useState('');const[busy,setBusy]=useState(false);const[status,setStatus]=useState('');const[name,setName]=useState('');
async function reload(){const r=await fetch('/api/book',{cache:'no-store'});const j=await r.json() as Data & {error?:string};if(!r.ok)throw Error(j.error);setData(j);setLoaded(true);return j as Data;}
useEffect(()=>{reload().catch(e=>setError(e.message));},[]);
async function act(body:object){setBusy(true);setError('');setStatus('Wird gespeichert …');try{const r=await fetch('/api/book',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const j=await r.json() as {error?:string};if(!r.ok)throw Error(j.error);await reload();setStatus('Gespeichert');return true;}catch(e){setError((e as Error).message);setStatus('Nicht gespeichert');return false;}finally{setBusy(false);}}
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const controller=new AbortController();Promise.resolve(context.registerTool({name:'read_meal_book',description:'Lädt die gespeicherten Teilnehmer und Essenseinträge und aktualisiert die Ansicht.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Keine Parameter erlaubt');return await reload();}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort();},[]);
const selected=data.meals.filter(x=>x.date===date);const day=new Date(date+'T12:00:00Z').getUTCDay();const valid=day===3||day===5;const wed=day===3;const monthMeals=data.meals.filter(x=>x.date.startsWith(month));const sum=(items:Meal[])=>items.reduce((n,x)=>n+x.cents,0);const shown=data.people.filter(p=>p.active||selected.some(m=>m.personId===p.id));
function step(n:number){const d=new Date(date+'T12:00:00Z');do{d.setUTCDate(d.getUTCDate()+n);}while(![3,5].includes(d.getUTCDay()));setDate(d.toISOString().slice(0,10));}
return <main><header><a className="brand" href="/"><span className="brandmark"><Utensils size={23}/></span>Dein Essensbuch<span className="brandtag">TEAM & TISCH</span></a><span className="save" role="status">{busy?'Wird gespeichert …':status||'Mittwoch & Freitag'}</span></header><div className="intro"><div><h1>Wer ist dabei?</h1></div><div className="pricelegend"><span><Utensils size={17}/> Mi · 4 €</span><span><Coffee size={17}/> Fr · 3 €</span></div></div>
<Tabs value={tab} onValueChange={setTab}><TabsList className="navigation"><TabsTrigger value="entry"><CalendarDays/>Erfassen</TabsTrigger><TabsTrigger value="report"><ChartNoAxesCombined/>Auswertung</TabsTrigger><TabsTrigger value="people"><Users/>Mitarbeiter</TabsTrigger></TabsList>
{error&&<div className="error" role="alert">{error} <button onClick={()=>reload().then(()=>setError('')).catch(e=>setError(e.message))}>Erneut laden</button></div>}
<TabsContent value="entry"><div className="workgrid"><section className="panel"><div className="sectionhead"><div><p className="eyebrow">TEILNAHME ERFASSEN</p><h2>{valid?(wed?'Mittagessen am Mittwoch':'Frühstück am Freitag'):'Essenstag wählen'}</h2></div><span className={'mealicon '+(wed?'blue':'orange')}>{wed?<Utensils/>:<Coffee/>}</span></div><div className="datebar"><button className="iconbutton" aria-label="Vorheriger Essenstag" onClick={()=>step(-1)}><ChevronLeft/></button><label><span className="sr-only">Datum</span><input type="date" value={date} onChange={e=>e.target.value&&setDate(e.target.value)}/></label><button className="iconbutton" aria-label="Nächster Essenstag" onClick={()=>step(1)}><ChevronRight/></button></div><div className="listcaption"><span>{shown.length} Mitarbeiter</span><span>{valid?euro(wed?400:300)+' pro Person':'Mittwoch oder Freitag auswählen'}</span></div>
{!loaded?<p className="empty">{error?'Daten nicht verfügbar.':'Einträge werden geladen …'}</p>:!shown.length?<div className="empty"><Users size={32}/><h3>Dein Team macht den Anfang.</h3><p>Lege zuerst die Mitarbeiter an. Danach genügt ein Häkchen pro Essen.</p><button className="primary" onClick={()=>setTab('people')}>Mitarbeiter hinzufügen</button></div>:<div className="peoplelist">{shown.map(p=>{const checked=selected.some(m=>m.personId===p.id);return <label className={'person '+(checked?'selected':'')} key={p.id}><span className="avatar">{p.name.slice(0,2).toUpperCase()}</span><span className="personname">{p.name}<small>{checked?'Isst mit':p.active?'Noch nicht eingetragen':'Archiviert'}</small></span><span className="amount">{checked?euro(wed?400:300):'—'}</span><Checkbox className="tick" aria-label={p.name+' isst mit'} checked={checked} disabled={!valid||busy||(!p.active&&!checked)} onCheckedChange={v=>act({action:'meal',date,personId:p.id,present:v===true})}/></label>})}</div>}
</section><aside><div className="totalpanel"><p className="eyebrow">DIESER ESSENSTAG</p><h2>{selected.length}<span> Personen essen mit</span></h2><div className="rule"/><p>Gesamtbetrag</p><strong>{euro(sum(selected))}</strong><p className="totalhint"><Check size={17}/> Jeder Eintrag wird direkt gespeichert.</p></div><div className="note"><h3>Zwei Tage. Ein Überblick.</h3><p>Mittwochs Mittagessen, freitags Frühstück. In der Auswertung findest du beide Beträge einzeln und zusammen.</p><button onClick={()=>{setMonth(date.slice(0,7));setTab('report')}}>Zur Monatsübersicht →</button></div></aside></div></TabsContent>
<TabsContent value="report"><section className="reporthead"><div><p className="eyebrow">MONATSÜBERSICHT</p><h2>Alles zusammengerechnet.</h2></div><label className="monthlabel">Monat<input type="month" value={month} onChange={e=>e.target.value&&setMonth(e.target.value)}/></label></section><div className="stats">{[['Mittwoch · Mittagessen','wed'],['Freitag · Frühstück','fri'],['Gesamt','all']].map(([label,kind])=><div className={'stat '+kind} key={kind}><p>{label}</p><strong>{euro(sum(monthMeals.filter(x=>kind==='all'||x.kind===kind)))}</strong><span>{monthMeals.filter(x=>kind==='all'||x.kind===kind).length} Essen</span></div>)}</div><div className="panel breakdown"><div className="sectionhead"><h2>Beiträge je Mitarbeiter</h2><span>{month}</span></div>{data.people.filter(p=>p.active||data.meals.some(m=>m.personId===p.id)).map(p=>{const meals=monthMeals.filter(m=>m.personId===p.id);const allMeals=data.meals.filter(m=>m.personId===p.id);return <article className="personreport" key={p.id}><h3>{p.name}</h3><div><span>Mittwoch <b>{euro(sum(meals.filter(m=>m.kind==='wed')))}</b></span><span>Freitag <b>{euro(sum(meals.filter(m=>m.kind==='fri')))}</b></span><span className="persontotal">Monat gesamt <b>{euro(sum(meals))}</b></span><span className="allmonthtotal">Alle Monate gesamt <b>{euro(sum(allMeals))}</b></span></div>{meals.length>0&&<details><summary>{meals.length} Essen · Termine anzeigen</summary><ul>{meals.map(m=><li key={m.date}>{new Date(m.date+'T12:00:00Z').toLocaleDateString('de-DE')} · {m.kind==='wed'?'Mittagessen':'Frühstück'} <b>{euro(m.cents)}</b></li>)}</ul></details>}</article>})}{!data.people.length&&<p className="empty">Noch keine Mitarbeiter angelegt.</p>}</div></TabsContent>
<TabsContent value="people"><section className="panel team"><div className="sectionhead"><div><p className="eyebrow">DEIN TEAM</p><h2>Mitarbeiter verwalten</h2></div><Users/></div><form onSubmit={async e=>{e.preventDefault();if(await act({action:'person',name}))setName('')}}><label htmlFor="name">Name</label><div className="addrow"><input id="name" placeholder="Vorname und ggf. Nachname" value={name} onChange={e=>setName(e.target.value)} maxLength={80} required/><button className="primary" disabled={busy||!loaded||!name.trim()}><Plus size={18}/> Hinzufügen</button></div></form><p className="muted">Archivierte Mitarbeiter bleiben in bisherigen Abrechnungen erhalten.</p>{data.people.map(p=><div className="teamrow" key={p.id}><span>{p.name}<small>{!p.active?'Archiviert':''}</small></span><button disabled={busy} onClick={()=>act({action:'active',id:p.id,active:!p.active})}>{p.active?'Archivieren':'Wieder aktivieren'}</button></div>)}</section></TabsContent></Tabs><footer>Dein Essensbuch <span>Mittwoch & Freitag</span></footer></main>;
}
